name=M5Autodetect
version=0.0.1
author=M5Stack
maintainer=M5Stack
sentence=Autodetect library for M5Stack
paragraph=Autodetect library for M5Stack
category=Device Control
url=https://github.com/onexs-xsi/M5Autodetect
architectures=*
includes=M5Autodetect.h
